/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizarr;

/**
 *
 * @author Paez
 */
public class ayudaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ayudaPanel
     */
    public ayudaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        bt_analizar = new javax.swing.JButton();
        bt_sintactico = new javax.swing.JButton();
        btn_sintac2 = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        tabbed = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_salida = new javax.swing.JTextArea();
        jScroll_entrada = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneErrores = new javax.swing.JScrollPane();
        txt_errores = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panelAyuda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(0, 113, 233));

        cabecera.setBackground(new java.awt.Color(0, 113, 233));

        bt_analizar.setBackground(new java.awt.Color(255, 255, 255));
        bt_analizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_analizar.setForeground(new java.awt.Color(0, 0, 51));
        bt_analizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/boton-de-play 2.png"))); // NOI18N
        bt_analizar.setText("Analizador Lexico");
        bt_analizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bt_analizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_analizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bt_analizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_analizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_analizar.setName(""); // NOI18N
        bt_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_analizarActionPerformed(evt);
            }
        });

        bt_sintactico.setBackground(new java.awt.Color(255, 255, 255));
        bt_sintactico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_sintactico.setForeground(new java.awt.Color(0, 0, 51));
        bt_sintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/tocar.png"))); // NOI18N
        bt_sintactico.setText("Analizador sintactico");
        bt_sintactico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bt_sintactico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_sintactico.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bt_sintactico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_sintactico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_sintactico.setName(""); // NOI18N
        bt_sintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sintacticoActionPerformed(evt);
            }
        });

        btn_sintac2.setBackground(new java.awt.Color(255, 255, 255));
        btn_sintac2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sintac2.setForeground(new java.awt.Color(0, 0, 51));
        btn_sintac2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/regreso.png"))); // NOI18N
        btn_sintac2.setText("Regresar a prueba");
        btn_sintac2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_sintac2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sintac2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_sintac2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sintac2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_sintac2.setName(""); // NOI18N
        btn_sintac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sintac2ActionPerformed(evt);
            }
        });

        btnAyuda.setBackground(new java.awt.Color(255, 255, 255));
        btnAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/ayuda.png"))); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_analizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_sintactico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sintac2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sintac2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbed.setBackground(new java.awt.Color(0, 113, 233));
        tabbed.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbed.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(0, 113, 233));

        txt_salida.setEditable(false);
        txt_salida.setColumns(20);
        txt_salida.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txt_salida.setForeground(new java.awt.Color(0, 0, 51));
        txt_salida.setRows(5);
        txt_salida.setSelectedTextColor(new java.awt.Color(0, 51, 204));
        txt_salida.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(txt_salida);

        txt_entrada.setBackground(new java.awt.Color(195, 221, 250));
        txt_entrada.setColumns(20);
        txt_entrada.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_entrada.setRows(5);
        txt_entrada.setText("inicio codigo RHA;:\nentero aux = 12:\nentero a = aux:\n\ndecimal dec = 1.4:\ndecimal a = 12.3:\n\ntexto c = 'hola como estas':\ntexto ho4 = 'hola mundo':\n\nsi ( aux = b ) {:\nsi ( uff > xd ) {:\n\nmientras ( aux = b ) {:\n\nmientras ( bb < asd ) {:");
        txt_entrada.setToolTipText("");
        txt_entrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(60, 63, 65), new java.awt.Color(60, 63, 65), null, new java.awt.Color(60, 63, 65)));
        txt_entrada.setSelectedTextColor(new java.awt.Color(102, 0, 102));
        txt_entrada.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScroll_entrada.setViewportView(txt_entrada);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisar/imagenes/warning.png"))); // NOI18N
        jLabel1.setText("E r r o r e s ");
        jLabel1.setOpaque(true);

        txt_errores.setEditable(false);
        txt_errores.setBackground(new java.awt.Color(232, 232, 232));
        txt_errores.setColumns(20);
        txt_errores.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_errores.setForeground(new java.awt.Color(255, 0, 0));
        txt_errores.setRows(5);
        jScrollPaneErrores.setViewportView(txt_errores);

        jLabel2.setText("ALEJANDRO PAEZ PEREZ Y ...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneErrores)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScroll_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScroll_entrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneErrores, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("tab2", jPanel4);

        panelAyuda.setBackground(new java.awt.Color(0, 113, 233));

        jPanel2.setBackground(new java.awt.Color(0, 113, 233));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ayuda\nanalizador lexico y sintactico hecho por\n\n--el codigo siempre tiene que iniciar por\n\tinicio codigo RHA;:\n\n--para declarar variables siempre se inicia el valor sea entero, decimal, texto seguido de el nombre de la variable\n\tentero aux = 12:\n\n--siempre se declara el valor en entero decimal y texto\n \tdecimal dec = 1.4:\n\ttexto c = 'hola como estas':\n\n--usar el si es facil siempre y cuando detecte bien los espacios para poder diferenciar\n\tsi ( aux = b ) {:\n\tsi ( uff > xd ) {:\n\n--usar el mientras hay que respetar si o si los cambios de mientras\n\tmientras ( aux = b ) {:\n\tmientras ( bb < asd ) {:\n\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAyudaLayout = new javax.swing.GroupLayout(panelAyuda);
        panelAyuda.setLayout(panelAyudaLayout);
        panelAyudaLayout.setHorizontalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAyudaLayout.setVerticalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("tab1", panelAyuda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed)
            .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tabbed))
            .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_analizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_analizarActionPerformed

    private void bt_sintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sintacticoActionPerformed

       // botonSintactico();
        txt_entrada.grabFocus();

        String crearG = "crear grupo [a-z]*";
        String sentenc = "crear|añadir|borrar";
        String senv = ""+sentenc+"+"+sentenc;

        System.out.println("es senbv es "+ senv);

        //    if ( prueba.matches(crearG+" donde permisos [{] "+sentenc+" [}]")){
            //        System.out.println("es correcto");
            //    }else {
            //        System.out.println("esta mal");
            //    }

        String prueba= "si ( letra < letra ) {";
        System.out.println(prueba.matches("(si [(] [a-z]* [<|>] [a-z]* [)] [{])"));

        //comparar();
    }//GEN-LAST:event_bt_sintacticoActionPerformed

    private void btn_sintac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sintac2ActionPerformed

       // btnsintac();

    }//GEN-LAST:event_btn_sintac2ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txt_salida.setText("");
        txt_errores.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_analizar;
    private javax.swing.JButton bt_sintactico;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btn_sintac2;
    private javax.swing.JPanel cabecera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneErrores;
    private javax.swing.JScrollPane jScroll_entrada;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTextArea txt_entrada;
    private javax.swing.JTextArea txt_errores;
    private javax.swing.JTextArea txt_salida;
    // End of variables declaration//GEN-END:variables
}
